<?php

    __('Select Service Type', 'calendar-booking');
    __('Select a Service', 'calendar-booking');
    __('Select a Provider', 'calendar-booking');
    __('Additional Options', 'calendar-booking');
    __('Select', 'calendar-booking');
    __('Selected', 'calendar-booking', 'calendar-booking');
    __('Select a Date & Time', 'calendar-booking');
    __('Available times for', 'calendar-booking');
    __('Searching Availability', 'calendar-booking');
    __('There are no available times for this date', 'calendar-booking');
    __('Morning', 'calendar-booking');
    __('Afternoon', 'calendar-booking');
    __('Evening', 'calendar-booking');
    __('Complete Appointment', 'calendar-booking');
    __('Email', 'calendar-booking');
    __('First Name', 'calendar-booking');
    __('Last Name', 'calendar-booking');
    __('Phone', 'calendar-booking');
    __('Submit', 'calendar-booking');
    __('Card Number', 'calendar-booking');
    __('Expiration', 'calendar-booking');
    __('Book and Pay Later', 'calendar-booking');
    __('Review Booking', 'calendar-booking');
    __('Services', 'calendar-booking');
    __('Addons', 'calendar-booking');
    __('Date & Time', 'calendar-booking');
    __('Duration', 'calendar-booking');
    __('Total', 'calendar-booking');
    __('Thank you for booking!', 'calendar-booking');
    __('We look forward to seeing you soon', 'calendar-booking');
    __('Return back', 'calendar-booking');
    __('Day', 'calendar-booking');
    __('Range', 'calendar-booking');
    __('There are no available classes for the selected dates', 'calendar-booking');
    __('Filter', 'calendar-booking');
    __('Searching Availability', 'calendar-booking');
    __('Remaining', 'calendar-booking');
    __('Sole Out', 'calendar-booking');
    __('Additional Options', 'calendar-booking');
    __('Complete Booking', 'calendar-booking');
    __('Classes', 'calendar-booking');
    __('Addons', 'calendar-booking');
    __('Continue', 'calendar-booking', 'calendar-booking');
    __('Back', 'calendar-booking');
    __('Book Now', 'calendar-booking');
    __('By clicking checkout you agree to our Terms of Service and Privacy Policy.', 'calendar-booking');
    __("home", 'calendar-booking');
    __("services", 'calendar-booking');
    __("classes", 'calendar-booking');
    __("packages", 'calendar-booking');
    __("login", 'calendar-booking');
    __("my account", 'calendar-booking');
    __("about us", 'calendar-booking');
    __("continue", 'calendar-booking');
    __("select", 'calendar-booking');
    __("remove", 'calendar-booking');
    __("back", 'calendar-booking');
    __("skip", 'calendar-booking');
    __("selected", 'calendar-booking');
    __("free", 'calendar-booking');
    __("forgot password", 'calendar-booking');
    __("remember me", 'calendar-booking');
    __("password", 'calendar-booking');
    __("next", 'calendar-booking');
    __("enter a valid address", 'calendar-booking');
    __("email address", 'calendar-booking');
    __("customer information", 'calendar-booking');
    __("customers", 'calendar-booking');
    __("sign in to your account", 'calendar-booking');
    __("reset password", 'calendar-booking');
    __("enter your email and we'll send you a link to reset your password", 'calendar-booking');
    __("we have securely populated a profile that matches this email address", 'calendar-booking');
    __("booking", 'calendar-booking');
    __("cancel", 'calendar-booking');
    __("book again", 'calendar-booking');
    __("booking cancelled", 'calendar-booking');
    __("service", 'calendar-booking');
    __("class", 'calendar-booking');
    __("date", 'calendar-booking');
    __("zoom", 'calendar-booking');
    __("join zoom", 'calendar-booking');
    __("charges", 'calendar-booking');
    __("paid", 'calendar-booking');
    __("view receipt", 'calendar-booking');
    __("ending in", 'calendar-booking');
    __("user", 'calendar-booking');
    __("first name", 'calendar-booking');
    __("last name", 'calendar-booking');
    __("mobile phone", 'calendar-booking');
    __("password requirements", 'calendar-booking');
    __("minimum 6 characters in length", 'calendar-booking');
    __("must contain at least one number", 'calendar-booking');
    __("continue without registering", 'calendar-booking');
    __("continue without email", 'calendar-booking');
    __("checkout", 'calendar-booking');

?>